chore: replace `yarn` with `npm`
The only reason is due to a heisenbug that appears after polyfilling `Buffer` and calling `crypto.createHash('sha256').update(passphrase).digest('hex')`

Error: `StringDecoder is not a constructor`